<a href="https://colab.research.google.com/github/SreeHarshaGudise/Python_For_Datascience/blob/Pandas_Basics/Pandas_Functionality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Manipulations

In [5]:
# Pandas Series Object
import pandas as pd
x = pd.Series([1,2,3,4,5])
print(x)
# As it contains the values and indices as attributes
print(x.values)
print(x.index)

# we can use non contiguos indices as well
y = pd.Series(data = [3.,4,5,1], index=[2,5,1,7])
print(y)

0    1
1    2
2    3
3    4
4    5
dtype: int64
[1 2 3 4 5]
RangeIndex(start=0, stop=5, step=1)
2    3.0
5    4.0
1    5.0
7    1.0
dtype: float64

In [7]:
# we can convert python dictionary to pandas series

x = pd.Series({2:'a',5:'c',3:'d'})
x

2    a
5    c
3    d
dtype: object

In [12]:
# Data Frame: Its a two dimensional series object as its a generilization of numpy array

population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)

states = pd.DataFrame({'area':area,'population': population})
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [16]:
# Pandas Index Object which is immutable array

p = pd.Index(data=[1,2,3,4,5])
p
p[0] = 3

TypeError: Index does not support mutable operations

In [15]:
# attributes of index object
p.size, p.shape, p.ndim

(5, (5,), 1)